version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: .devcontainer/frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: yarn dev
    ports:
      - "3001:3000"